server {
  listen 80;
  root /usr/share/nginx/html;

  location /api/ {
    proxy_pass http://backend:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # una single page application serve index.html per ogni percorso
  location / {
    try_files $uri $uri/ /index.html;
  }
}
